### ISSUE TITLE
Is there any special design for low light enhancement?

### ISSUE THREAD

**Issue by order-a-lemonade** [ZhexinLiang/CLIP-LIT#14]
can we just change the dataset for other image enhancement tasks?

**Comment by ZhexinLiang** [comment]
Hi @order-a-lemonade, thanks for you interest in our work.

I think for other image enhancement task, you can try more classic network, like Restormer, because our network is relatively simple and maybe cannot handle more complex tasks. For example, you can add a deraining block for deraining tasks. Based on my experiments, directly using our method can do deraining but the performance is not SOTA.

Feel free to contact me if you have any other questions.

**Comment by order-a-lemonade** [comment]
> Hi @order-a-lemonade, thanks for you interest in our work.
> 
> There is no special design for low light enhancement (maybe using the PPM block can be a small design). I think for other image enhancement task, you can try more commonly-used network, like Restormer, because our network is relatively simple and maybe cannot handle more complex tasks. For example, you can add a deraining block for deraining tasks. Based on my experiments, directly using our method can do deraining but the performance is not SOTA.
> 
> Feel free to contact me if you have any other questions.

An awesome work! and thanks for your reply.
